### ISSUE TITLE
Old github URL in docker automated build?!?

### ISSUE THREAD

**Issue by waja** [fradelg/docker-mysql-cron-backup#9]
https://hub.docker.com/r/fradelg/mysql-cron-backup/ indicates that https://github.com/fradelg/docker-images is the source for the automated build.

**Comment by fradelg** [comment]
Don't trust Docker Hub since it still preserves deprecated settings. I moved to Docker Cloud a year ago and the repo settings for building are correct. Actually, last last builds come from this repo.

![docker-cloud-builds](https://user-images.githubusercontent.com/3170844/35562459-bfa1b8ac-05b3-11e8-9b66-1c80b4ad056c.jpg)
